// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mainR
void mainR(const StringVector& arguments);
RcppExport SEXP _treeBreaker_mainR(SEXP argumentsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type arguments(argumentsSEXP);
    mainR(arguments);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treeBreaker_mainR", (DL_FUNC) &_treeBreaker_mainR, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_treeBreaker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
